### PR TITLE
Implementing Auto Update Author Blacklist

### PR DESCRIPTION
**Pull request by Negan1911**
Hello @chdsbd thanks again for your great bot!, 

I've made an approach into the `update.username_blacklist` flag that we discussed on #326, since I'm new to Python (first code written ever, I'm a JS guy 😅) I may have made some mistakes so let me know what I should correct.
 
I renamed it to `blacklist_usernames` to share the same approach taken by `auto_approve_usernames` and `blacklist_labels` and also wrote a test covering the case (which looks to be passing).

My only issue is with schema, giving the following error:
```py
___________________________________________________________ test_config_schema ___________________________________________________________

    def test_config_schema() -> None:
        schema_path = load_config_fixture("config-schema.json")
>       assert json.loads(V1.schema_json()) == json.loads(
            schema_path.read_text()
        ), "schema shouldn't change unexpectedly."
E       AssertionError: schema shouldn't change unexpectedly.
E       assert {'definitions...e': 'V1', ...} == {'definitions'...e': 'V1', ...}
E         Omitting 3 identical items, use -vv to show
E         Differing items:
E         {'properties': {'app_id': {'title': 'App Id', 'type': 'string'}, 'approve': {'allOf': [{'$ref': '#/definitions/Approve...}], 'default': {'always': False, 'blacklist_usernames': [], 'require_automerge_label': True}, 'title': 'Update'}, ...}} != {'properties': {'app_id': {'title': 'App Id', 'type': 'string'}, 'approve': {'allOf': [{'$ref': '#/definitions/Approve...ef': '#/definitions/Update'}], 'default': {'always': False, 'require_automerge_label': True}, 'title': 'Update'}, ...}}
E         {'definitions': {'Approve': {'pr...
E         
E         ...Full output truncated (2 lines hidden), use '-vv' to show

kodiak/test_config.py:116: AssertionError
```

It would be great if you could review this one and give me some help on how to avoid this error :)
Thanks again!

### CODE REVIEW

**Comment by chdsbd** [comment]
I tested the changes and it seems to work.

image

I feel like this status message could be improved though.

**Comment by chdsbd** [comment]
Regarding the failing `test_config_schema`, I had to run `poetry run kodiak gen-conf-json-schema > kodiak/test/fixtures/config/config-schema.json` to update that. I should probably better document that in the test failure.

**Comment by chdsbd** [comment]
@Negan1911 Let me know if you have any feedback for my changes or if I'm good to merge this PR.

**Comment by Negan1911** [comment]
You're good to go, thanks for the quick response!

**Comment by chdsbd** [comment]
Thanks for the PR!

**Comment by chdsbd** [comment]
This change has been deployed to production.

**Pull request merged**
