### PR TITLE
Support fast-forward rebase strategy

### PR DESCRIPTION
**Pull request by brock8503**
Add "rebase-fast-forward" merge option that uses the GitHub Refs API to merge a pull request instead of the GitHub Pull Requests API. This way commits aren't rewritten on merge like they are with the pull request API.

---

Hi @chdsbd, 

My team and I have been very interested in making progress on https://github.com/chdsbd/kodiak/issues/150 as we noted in our comments in that issue. My colleague @andrewhamton and I found time to put this change together which implements a fast-forward merge from `branch` into `base`. We are very interested in merging these changes into your upstream. We've been running our fork internally. So this code has seen production use at our company [Poll Everywhere](https://polleverywhere.com). 

I've noticed you may have started looking into this already at https://github.com/chdsbd/kodiak/pull/608. Let us know if we can collaborate to move either solution forward. 

In summary, the ideal behavior for rebasing in a CI workflow is:

* PR is automatically rebased on the base branch if it falls behind the base branch
* CI builds successfully at PR head
* PR is merged by *fast-forwarding* base branch to PR head
* No further builds or verifications are required to validate the base branch because
  the refs match between base and head

The two ideal requirements:

* Rebasing when the base branch is updated instead of merging changes into the PR
  * Rebasing a PR on the base branch is not possible to perform with the PR api https://docs.github.com/en/rest/reference/pulls#merge-a-pull-request
  * A merge commit will always be created to update the PR branch
* Performing a fast-forward merge onto the base branch when the PR is ready
  * Can be achieved with the Github Ref update APIs https://docs.github.com/en/rest/reference/git#refs

This change ensures the same SHA that has passed CI checks will become the head of the base branch. Additional work is required to create a clean git history without merge commits if a branch falls behind the base.

### CODE REVIEW

**Comment by chdsbd** [comment]
Thanks for opening this pull request. I'm definitely interested in merging this change and resolving #150. That's been a long standing issue. I'll probably close #608 in favor of this pull request.

Adding rebase updates is a bit more involved since it requires making multiple API calls, as mentioned here: https://github.com/chdsbd/kodiak/issues/150#issuecomment-668916454 But feel free to ping me with questions.

It will probably take me a bit to verify and merge this PR.

**Comment by chdsbd** [comment]
@brock8503 have you considered using the Git tree hash for build deduplication instead of the commit hash?

I think the tree hash will be the same after rebasing through the GitHub UI, while the commit hash will change.

**Comment by brock8503** [comment]
@chdsbd I honestly didn't look into that. I'm going to pull in your latest changes and verify them on our side. Thanks again for the help.

**Comment by chdsbd** [comment]
I tested locally and this change appears to work. The commits don't get rewritten on merge like they do with the GitHub UI.

**Review by sbdchd — APPROVED** [review]

**Comment by brock8503** [comment]
@chdsbd Thank you so much for pushing this forward.

**Pull request merged**
