### PR TITLE
deps: update uvicorn to 0.15.0

### PR DESCRIPTION
**Pull request by jbergstroem**
..alongside its dependencies.

This change was introduced by invoking `poetry update uvicorn` after updating `pyproject.toml`.

Hoping that CI will cover more test setups than mine.

### CODE REVIEW

**Comment by jbergstroem** [comment]
So, pip fails with:
```
Creating virtualenv kodiak-py3.7 in /root/project/bot/.venv
Installing dependencies from lock file
                                  
[NonExistentKey]   
'Key "hashes" does not exist.'  
                                  
install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]
```

According to google, this is likely due to using an old version of poetry. Should I update that as well in this PR?

**Comment by chdsbd** [comment]
@jbergstroem Yeah, we're on an old version of poetry ([0.12.12](https://github.com/chdsbd/kodiak/blob/4c4ff6c2665796f640c5d32b013e042a6d0112b2/.circleci/config.yml#L31)). I'm not opposed to upgrading our poetry version if you're up for it. We need to update `bot/` and `web_api/` as well as the CircleCI config.

**Comment by jbergstroem** [comment]
> @jbergstroem Yeah, we're on an old version of poetry (`0.12.12`). I'm not opposed to upgrading our poetry version if you're up for it. We need to update bot/ and web_api/ as well as the CircleCI config.

Will do a new PR later today to keep things separate.

**Comment by jbergstroem** [comment]
(will rebase once poetry lands)

**Comment by jbergstroem** [comment]
Rebased but fails fast in CI; looks like old poetry is still being pulled. The circleci cache documentation is easy to read; so is the config. Even the cache step says "no cache". What am I missing? Is it related to force pushing to the branch?

**Comment by chdsbd** [comment]
@jbergstroem The PR looks good to me. It seems like it's passing CI at the moment

**Review by chdsbd — APPROVED** [review]

**Pull request merged**
