### PR TITLE
deps: update poetry to 1.1.8

### PR DESCRIPTION
**Pull request by jbergstroem**
This bumps the pinned installation of poetry for building containers as well as setting up CI.

### CODE REVIEW

**Comment by jbergstroem** [comment]
Checking the logic for building a docker image, I would suggest decoupling auth/logging in to docker hub for testing if the container builds. I would do a separate action/ci job that only runs on tags and uploads instead.

**Review by chdsbd — APPROVED** [review]
Thanks for the PR!

**Comment by chdsbd** [comment]
@jbergstroem I like building the containers for every commit so that I can test any commit in a staging environment

**Comment by jbergstroem** [comment]
> @jbergstroem I like building the containers for every commit so that I can test any commit in a staging environment

You mean pulling it manually? If so, ok, got it!

**Comment by chdsbd** [comment]
@jbergstroem I'm not sure why, but this change isn't passing the build.

Regarding the containers, yeah, I manually specify the SHA to deploy

**Comment by jbergstroem** [comment]
> @jbergstroem I'm not sure why, but this change isn't passing the build.

Strange; it was all green yesterday. The failures I see right now seems docker auth related?

**Comment by jbergstroem** [comment]
@chdsbd I was able to reproduce locally with python 3.7 (but not with 3.9 which was my homebrew default). I think you had it by updating ipdb but not updating the lockfile at the same time probably bit you. Will force push an update which should change lockfile.

**Comment by jbergstroem** [comment]
@chdsbd there's a failed test due to outdated (?) fixtures:

```python traceback
______________________________ test_config_schema ______________________________

    def test_config_schema() -> None:
        """
        Although we don't use the config schema anywhere, it provides a form of
        documentation for the bot config.
        """
        schema_path = load_config_fixture("config-schema.json")
>       assert json.loads(V1.schema_json()) == json.loads(schema_path.read_text()), (
            "schema shouldn't change unexpectedly.\n"
            "Did you remember to run `poetry run kodiak gen-conf-json-schema > kodiak/test/fixtures/config/config-schema.json` in the `bot` directory?"
        )
E       AssertionError: schema shouldn't change unexpectedly.
E         Did you remember to run `poetry run kodiak gen-conf-json-schema > kodiak/test/fixtures/config/config-schema.json` in the `bot` directory?
E       assert {'definitions...e': 'V1', ...} == {'definitions...e': 'V1', ...}
E         Omitting 4 identical items, use -vv to show
E         Differing items:
E         {'definitions': {'Approve': {'properties': {'auto_approve_usernames': {'default': [], 'items': {'type': 'string'}, 'ti...|reserved|||:::', 'title': 'Blacklist Title Regex', 'type': 'string'}, ...}, 'title': 'Merge', 'type': 'object'}, ...}} != {'definitions': {'Approve': {'properties': {'auto_approve_usernames': {'default': [], 'items': {'type': 'string'}, 'ti... {'default': '', 'title': 'Cut Body Before', 'type': 'string'}, ...}, 'title': 'MergeMessage', 'type': 'object'}, ...}}
E         Use -v to get the full diff

kodiak/test_config.py:120: AssertionError
```

Let me know what you want me to do.

**Comment by jbergstroem** [comment]
soo.. this is getting a bit out of hand 😄 Should I venture down the rabbit hole of lint fixes?

**Pull request merged**
