### PR TITLE
add(bot): merge.automerge_labels config option

### PR DESCRIPTION
**Pull request by chdsbd**
Add new config option (`merge.automerge_labels`) to allow specifying additional automerge_labels.

related: https://github.com/chdsbd/kodiak/issues/476#issuecomment-702077444

### CODE REVIEW

**Comment by chdsbd** [comment]
@clxmstaab I think this addresses your request in https://github.com/chdsbd/kodiak/issues/476#issuecomment-701988962.

One issue is that with `merge.notify_on_conflict`, `kodiak:merge.method='squash'` would get removed from the pull request if you had it as the automerge_label. Is that a blocker for your use case?

**Review by sbdchd — APPROVED** [review]

**Comment by clxmstaab** [comment]
> One issue is that with `merge.notify_on_conflict`, `kodiak:merge.method='squash'` would get removed from the pull request if you had it as the automerge_label. Is that a blocker for your use case?

I dont think this is a problem.

after resolving conflicts one need to re-add the automerge-label.. when its only a single label thats perfectly fine.

**Comment by chdsbd** [comment]
I'll update this PR when this change is deployed. I usually deploy changes on Saturday.

**Comment by chdsbd** [comment]
This change has been released with https://github.com/chdsbd/kodiak/releases/tag/v0.30.0.

**Pull request merged**
